---
version: '3.8'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    restart: always
    ports:
      - "${MINIO_PORT}:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    expose:
      - "9000"
      - "9001"
    networks:
      - app

  minio-init:
    image: minio/mc:latest
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c "
        sleep 5;
        mc alias set local http://minio:9000 ${MINIO_ROOT_USER} ${MINIO_ROOT_PASSWORD};
        mc mb -p local/${MINIO_DATASET_BUCKET} || true;
        mc mb -p local/${MINIO_RESULTS_BUCKET} || true;
      "
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_DATASET_BUCKET: ${MINIO_DATASET_BUCKET}
      MINIO_RESULTS_BUCKET: ${MINIO_RESULTS_BUCKET}
    networks:
      - app

volumes:
  minio_data:

