---
version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - ./frontend/node_modules:/app/node_modules
    command: npm run dev
    env_file:
      - .env
    networks:
      - app

  node-api:
    build: ./node-api
    ports:
      - "3000:3000"
    volumes:
      - ./node-api/src:/app/src
      - ./node-api/drizzle:/app/drizzle
      - ./node-api/drizzle.config.ts:/app/drizzle.config.ts
      - ./node-api/tsconfig.json:/app/tsconfig.json

    depends_on:
      - postgres
      - keycloak
    env_file:
      - .env
    networks:
      - app

  python-api:
    build: ./python-api
    ports:
      - "3001:3001"
    volumes:
      - ./python-api:/app
    command: uvicorn main:app --reload --host 0.0.0.0 --port 3001
    networks:
      - app

  caddy:
    image: caddy:latest
    ports:
      - "80:80"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
    networks:
      - app

networks:
  app:
    driver: bridge
